### ISSUE TITLE
"The blood of poor Americans is now a leading export, bigger than corn or soy"

### ISSUE THREAD

**Issue by coffenbacher** [alexandersimoes/oec#262]
https://boingboing.net/2019/12/09/leeched.html
https://www.mintpressnews.com/harvesting-blood-americas-poor-late-stage-capitalism/263175/

These articles are sourced off of this page, which visualizes HS92 3002: https://oec.world/en/visualize/tree_map/hs92/export/usa/show/3002/2017/

The issue with this is that it pretty clearly states "Human and Animal Blood" as the product but HS92 3002* includes human and animal vaccines, which are the overwhelming majority of those exports. Is there a way to clear up the descriptions or add additional details on the main page, so people checking sources can easily find that out? I even saw a number of commenters on HN go to the effort of checking the article's source, but the misleading title led them to believe it was actually correct.

https://news.ycombinator.com/item?id=21762633

**Comment by alexandersimoes** [comment]
Hi thanks for bringing this up! As you and someone else in the hacker news article mentioned, the data is correct but the label is misleading as Vaccines are also part of the HS 3002 product classification. I have since gone in and updated the label.

https://oec.world/en/profile/hs92/3002/

<img width="1037" alt="Screen Shot 2019-12-11 at 2 33 55 PM" src="https://user-images.githubusercontent.com/252276/70653876-4a0cb000-1c23-11ea-81aa-c8ff4da4e444.png">

**Comment by coffenbacher** [comment]
Thanks for fixing this so quickly!!! Looks much better.
