### ISSUE TITLE
Discrepancies between some countries total exports in the OCE and COMTRADE

### ISSUE THREAD

**Issue by dylanjcastillo** [alexandersimoes/oec#84]
Hello,

Recently, I've been working using the OCE datasets in a research that compares ASEAN, LAC and the Arab League. While the data provided has been very useful for me and the rest of the team (and we are very thankful for that), we've recently seen some issues in the databases that have worried us:

1. For ASEAN and Arab League countries (we have not tested this for other countries), using the database "year_origin_destination_sitc.tsv.bz2", we've found that the rows corresponding to the years 1997 and 1998 are duplicated. By comparing this values with the ones from database made with the HS classifications codes, we concluded that the row that is not correct is the one corresponding to the year 1998, since it showed a major difference during this comparison.

You can corrobore this fact by constructing a visualization in the OCE app for Singapore using the years mentioned and the SITC classification. 

2.  The other issue we've seen while using this database is that there are major discrepancies in some countries between the data provided by COMTRADE and yours. In the case of Venezuela, there's a 30$B or 60$B difference (depending if the HS or SITC classification was used) in the total exports for the year 2012  (the value reported by COMTRADE was 90$B, so that difference seems very high). Additionally, many countries of CARICOM show very large discrepancies in the value of their flows. We do not truly understand why this happens and we would like to know if there is something specific in methodology you are using that could cause that.

We've been processing the data using R and STATA, if you think that seeing our code could be of any help we will gladly share it with you.

Regards,

Dylan

**Comment by alexandersimoes** [comment]
Thanks for bringing up these issues. I've created a new ticket (#85) for the first issue mentioned.

The second issue is most likely related to the source data. We are using raw COMTRADE for the SITC data from 2001 onward and CEPII's [BACI](http://www.cepii.fr/CEPII/en/bdd_modele/presentation.asp?id=1) database for all HS data. Please check to see if these sources have the same discrepancies you've mentioned if so I would trust the BACI database moving forward since they have a [well trusted and academically published methodology](http://www.cepii.fr/CEPII/fr/publications/wp/abstract.asp?NoDoc=2726) for cleaning the COMTRADE dataset. The only reason we don't use them as a source for the SITC data is because they don't publish it :-(.
